#+TITLE: VAST Fits
#+PROPERTY: header-args :tangle yes

* Setup

#+BEGIN_SRC R :session *R-vast*
library(tidyverse)
## library(VAST)
## library(FishStatsUtils)
devtools::load_all("~/src/FishStatsUtils", helpers = FALSE, export_all = FALSE)
devtools::load_all("~/src/VAST", helpers = FALSE, export_all = FALSE)
devtools::load_all("~/src/spatq", helpers = FALSE)
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :session *R-vast*
## coordref <- read_csv("coordref.csv",
##                      col_types = cols(
##                        loc_idx = col_integer(),
##                        s1 = col_double(),
##                        s2 = col_double()))
## catch_df <- read_csv("repl_01/catch_01_pref.csv",
##                      col_types = cols(
##                        time = col_integer(),
##                        vessel_idx = col_integer(),
##                        loc_idx = col_integer(),
##                        coordinates = col_character(),
##                        effort = col_double(),
##                        catch_biomass = col_double())) %>%
##   left_join(coordref, by = "loc_idx") %>%
##   select(-coordinates, -loc_idx)
## write_csv(catch_df, "catch_sim.csv")
#+END_SRC

#+RESULTS:

** Import simulated data
Data are simulated by =FisherySim.jl= through the =SpatQSims.jl= Julia packages.
The R =spatq= package includes convenient mechanisms for importing these data
sets.

#+BEGIN_SRC R :session *R-vast*
catch_df <- read.csv("catch_sim.csv") %>%
  mutate(s1 = (s1 - 50) / 100,
         s2 = (s2 - 50) / 100) %>%
  filter(time <= 10)
#+END_SRC

#+RESULTS:

First create the extrapolation grid. Here keeping everything centered on the
equator/prime meridian intersection within a 1°×1° box to minimize issues with
Lon/Lat conversions.

#+BEGIN_SRC R :session *R-vast*
extrap_grid <- cross_df(list(Lon = (seq(0.5, 99.5, 1) - 50) / 100,
                             Lat = (seq(0.5, 99.5, 1) - 50) / 100)) %>%
  mutate(Area_km2 = 1) %>%
  as.matrix

vast_extrap <- make_extrapolation_info(Region = "user",
                                       zone = NA,
                                       strata.limits =
                                         data.frame(STRATA = "All_areas"),
                                       input_grid = extrap_grid)
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :session *R-vast*
vast_spat <- make_spatial_info(n_x = 404,
                               Lon_i = catch_df$s1,
                               Lat_i = catch_df$s2,
                               Extrapolation_List = vast_extrap,
                               Method = "Mesh",
                               fine_scale = TRUE,
                               Save_Results = FALSE,
                               refine = TRUE)
#+END_SRC

#+RESULTS:

This provides a usable mesh, albeit not one that matches the default in =spatq=.

#+RESULTS:

#+BEGIN_SRC R :session *R-vast*
vast_data <- make_data(b_i = catch_df$catch_biomass,
                       a_i = catch_df$effort,
                       ## c_iz needs to be zero-indexed, as
                       ## VAST/R/make_data.R:155 assigns `n_c = max(c_iz) + 1`
                       c_iz = matrix(rep_along(catch_df$catch_biomass, 0)),
                       t_i = catch_df$time,
                       FieldConfig = c(Omega1 = 1, Epsilon1 = 0,
                                       Omega2 = 1, Epsilon2 = 0),
                       ObsModel_ez = c(PosDist = 1, Link = 1),
                       spatial_list = vast_spat,
                       Aniso = FALSE,
                       CheckForErrors = TRUE)
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :session *R-vast*
vast_model <- make_model(TmbData = vast_data,
                         Version = get_latest_version())
#+END_SRC

#+RESULTS:
: TRUE

#+BEGIN_SRC R :session *R-vast*
vast_fit <- optim(vast_model$Obj$par, vast_model$Obj$fn, vast_model$Obj$gr,
                  method = "BFGS")
vast_sdr <- sdreport(vast_model$Obj)
#+END_SRC

#+RESULTS:

So VAST /is/ giving a PD hessian with the first replicate of the simulated data.
Not sure what the differences are, but both =logkappa= parameters are small(-3.5
ish), equivalent to correlation range of roughly 90. That's probably consistent
with the simulated data.

Of note is that the condition number of the fixed-effect covariance matrices is
fairly large - should expect to lose src_R[:session
*R-vast*]{log10(kappa(vast_sdr$cov.fixed))} {{{results(=8.48753029091291=)}}}
digits to numerical error.

#+BEGIN_SRC R :session *R-vast*
time_string <- format(Sys.time(), "%Y-%m-%dT%H:%M")
saveRDS(vast_sdr, paste0("vast_sdr_", time_string, ".RData"))
#+END_SRC

#+RESULTS:

#+BEGIN_SRC R :session *R-vast*
vast_model_v1 <- make_model(TmbData = vast_data,
                            Version = "v1_0_0")
#+END_SRC

#+RESULTS:


** [2020-04-21 Tue]
Ran this VAST fit again. For some reason, now gives non-PD Hessian. Fixed effect
parameters are different. In particular, all beta1 parameters are approximately
0.155 larger and beta2 are 0.023 higher. Is this an identifiability issue?

** [2020-04-22 Wed]
Ran it again, still non-PD Hessian. Starting from the fixed parameter values
that /did/ give a PD Hessian, a PD Hessian can be found again. So it (partially,
at least) comes down to nonlinear optimization issues. Of note is that the =mgc=
from ~sdreport~ is still ~4, which doesn't give me a lot of confidence that
we're in the right place. But maybe this is normal?

Eigendecomposition of =cov.fixed= gives a largest eigenvalue of 4.5e3, quickly
decreasing by multiple orders of magnitude. Process 1 parameters are 1e-5, while
process 2 are 1e-1, which probably (?) indicates that these are the problematic ones.

Looking at the correlation matrix (from =cov.fixed=), the beta parameters are
all /super/ correlated; there are two blocks where off-diagonal entries are
~0.9999. This definitely seems like a problem. Is this normal in VAST?
** [2020-08-05 Wed]
Looking back at these results to see where the non-PD Hessian is coming from in
fits 2 and 3 here. Could not get above code to run with latest version of VAST.
"NOT A VECTOR!" warning from TMB for some reason.

#+BEGIN_SRC R :session *R-vast*
sdr1 <- readRDS("VAST-run/vast_sdr_2020-04-17T13:24.RData")
sdr2 <- readRDS("VAST-run/vast_sdr_2020-04-22T10:05.RData")
sdr3 <- readRDS("VAST-run/vast_sdr_2020-04-22T10:26.RData ")

eig1 <- eigen(sdr1$cov.fixed)
eig2 <- eigen(sdr2$cov.fixed)
eig3 <- eigen(sdr3$cov.fixed)
#+END_SRC

#+RESULTS:
|    -3772.99190091845 |
|     38.6590165589487 |
|     2.02060065850653 |
|   0.0963698880669193 |
|  0.00833326613450672 |
|  0.00817087032635617 |
|  0.00811804970388517 |
|  0.00810496176646841 |
|  0.00807890498478738 |
|  0.00801136335567165 |
|  0.00799942814953216 |
|  0.00799640724106876 |
|  0.00797194335829657 |
|   0.0079344403244212 |
|  0.00790499127239198 |
|  0.00789284307030435 |
|  0.00787686790874847 |
|  0.00785359374890457 |
|  0.00783506682204719 |
|  0.00782199521231538 |
|  0.00778112530508233 |
|   0.0077598495017162 |
|  0.00769057797717946 |
|  0.00764384716652228 |
|   0.0076155003758428 |
|  0.00759736778418465 |
|  0.00753527843554946 |
|  0.00750045949475921 |
|  0.00498504560564399 |
|  0.00127609038786829 |
| 0.000569654232721966 |
| 0.000569218406382989 |
| 0.000562398087122355 |
|  0.00056212139012409 |
| 0.000561043403113236 |
| 0.000560447362899587 |
| 0.000559050068104373 |
| 0.000556652401923491 |
| 0.000556226993864434 |
| 0.000555686754984075 |
| 0.000555610600692517 |
| 0.000555553995269227 |
| 0.000555322904833738 |
| 0.000555101312568083 |
| 0.000554969774229765 |
| 0.000554926725682745 |
| 0.000554702721216551 |
| 0.000554469842210872 |
| 0.000554143635021089 |
| 0.000553848139410038 |
| 0.000553831287401504 |
| 0.000553760611714883 |
|  0.00055347692671633 |
| 0.000553021135086747 |
| 8.94717835138555e-06 |

#+BEGIN_SRC R
parnames <- names(sdr1$par.fixed)
parnames[rank(eig2$vectors[, 1])]
#+END_SRC

#+RESULTS:
